# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.2.81-1.21.1+fabric
maven_group=net.astralya.hexalia
archives_base_name=hexalia

# Dependencies
fabric_version=0.116.5+1.21.1
geckolib_version=4.7.6

# Optional Dependencies
rei_version=16.0.799
patchouli_version=1.21.1-92