modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="hexalia"
version="1.0.1-1.20.1+forge"
displayName="Hexalia"
authors="Grape Studios"

description='''A magical mod focused on herbology and potion brewing.'''

[[dependencies.hexalia]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexalia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexalia]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.0.1.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexalia]]
    modId="geckolib"
    mandatory=true
    versionRange="[1.20.1-84-FORGE,)"
    ordering="NONE"
    side="BOTH"